Implement multiple transaction simulation
blowfishxyz/solana-private-fork pull request #1
Opened 2022-09-27 13:17 UTC by LogvinovLeon

#### Problem

#### Summary of Changes

Fixes #

2022-09-27 13:48 UTC, fabioberger requested changes

2022-09-30 14:37 UTC, fabioberger requested changes

2022-09-30 14:37 UTC, fabioberger commented on rpc/src/rpc.rs
> +                    overrides = AccountOverrides::default();
Hm, this means we're clearing all the account overrides from the previous execution. So if `accountA` was changed in tx 1, and then references in tx 3, tx 3 won't execute on top of the changes from tx 1. This is wrong. The updates to the overrides should be cumulative across all transactions executed. Please add a test with 3 txns, where 1 and 3 modify the same account.

2022-09-30 14:37 UTC, fabioberger commented on rpc/src/rpc.rs
> +            tx1_serialized_encoded,
I'm pretty sure this should return a 400.

2022-09-30 14:37 UTC, fabioberger commented on rpc/src/rpc.rs
> +            failing_tx_serialized_encoded,
Ditto here.

2022-10-03 08:42 UTC, LogvinovLeon commented on rpc/src/rpc.rs
> +                    overrides = AccountOverrides::default();
Hm. No. In the next 3 lines we are refilling the overrides with all the account states after the simulation. And that survives the simulation errors. I've added a test to demonstrate that case in which we have:
```
Transfer X
Fail
Transfer 2X
```
 and end up with a balance of `3X`.

2022-10-03 08:53 UTC, LogvinovLeon commented on rpc/src/rpc.rs
> +            failing_tx_serialized_encoded,
I don't agree here. This transaction is a valid transaction as far as all the static checks go. You can not discard it before actually executing it. And this method does exactly that. The way I understand 400 - it's for pre-work checks. One other argument here is that if you pass this tx into original simulator - you get it simulated and error logs instead of 400.
```
                            "Program 11111111111111111111111111111111 invoke [1]",
                            "Transfer: insufficient lamports 1000000, need 18446744073709551615",
                            "Program 11111111111111111111111111111111 failed: custom program error: 0x1",
```

We can obvsly change our 400 scope, but it doesn't feel right as wrong transactions not bricking the simulator is exactly what we're trying to achieve. WDYT?

2022-10-03 08:55 UTC, LogvinovLeon commented on rpc/src/rpc.rs
> +            tx1_serialized_encoded,
Here I'm less sure than the next one, but still. Returning 400 doesn't return any results and bricks. This solution is better (in my opinion) as we at least get partial results.

2022-10-03 10:19 UTC, LogvinovLeon commented on rpc/src/rpc.rs
> +                    if tx_hashes.contains(transaction.message_hash()) {
If someone submits an already mined transaction - the simulation endpoint simulates it and ignores the fact that it's already mined if the recent blockhash is still recent

2022-10-03 11:15 UTC, fabioberger commented on rpc/src/rpc.rs
> +                    if tx_hashes.contains(transaction.message_hash()) {
Oh wow, that's surprising. Ok, so then we can leave this as is.

2022-10-03 13:54 UTC, fabioberger requested changes

2022-10-03 14:03 UTC, fabioberger approved these changes

2022-10-03 14:04 UTC, merged